version: '3.4'

services:
  santexchallenge:
    image: santexchallenge
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 8081:8081
